spring:
  datasource:
    url: jdbc:mysql://localhost:3308/310gllyjd?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
      allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
server:
  port: 8088
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public
  compression:
    enabled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
